### ISSUE TITLE
Unable to verify the contract on the blockchain browser

### ISSUE THREAD

**Issue by Alexliu007** [second-state/substrate-ssvm-node#12]
**Description**
Unable to verify the contract on the blockchain browser

My contract address:
0xe01169a8d0cd5d8f7ad995be308abf90765cf4b5

My contract code:
https://github.com/Alexliu007/Deploy-a-Solidity-smart-contract-on-ParaState-s-testnet/blob/main/USDTToken.sol

**Steps to Reproduce**

**Expected vs. Actual Behavior**
expected:
success.

but i got this error:
ReferenceError: err is not defined
    at /home/wangshishuo/scan.parastate.io/routes/contract.js:47:16

**Environment**
Mac os

**Logs, Errors or Screenshots**
err is not defined
ReferenceError: err is not defined
    at /home/wangshishuo/scan.parastate.io/routes/contract.js:47:16
    at nextTask (/home/wangshishuo/scan.parastate.io/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/home/wangshishuo/scan.parastate.io/node_modules/async/dist/async.js:5334:5)
    at /home/wangshishuo/scan.parastate.io/routes/contract.js:45:9
    at Layer.handle [as handle_request] (/home/wangshishuo/scan.parastate.io/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/wangshishuo/scan.parastate.io/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/wangshishuo/scan.parastate.io/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/wangshishuo/scan.parastate.io/node_modules/express/lib/router/layer.js:95:5)
    at /home/wangshishuo/scan.parastate.io/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/wangshishuo/scan.parastate.io/node_modules/express/lib/router/index.js:330:12)

![image](https://user-images.githubusercontent.com/33770261/115133213-ff7e1d80-a038-11eb-8059-bac136b61193.png)

**Additional Information**

**Comment by DarumaDocker** [comment]
There is something wrong with this function. We have closed it for now and will reopen it when we fix it.
